version: '3.8'

services:
  api:
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  refresh_invoker:
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 30M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  proxy:
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
